#!/usr/bin/env node
/**
 * Regenerates docs/BACKLOG.md from docs/backlog/*.md YAML frontmatter.
 *
 * No YAML dependency: the frontmatter subset we use is small and regular.
 * Output must not contain U+2014 (en-dashes are fine).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const BACKLOG_DIR = path.join(ROOT, "docs", "backlog");
const OUT = path.join(ROOT, "docs", "BACKLOG.md");

const STATUS = {
  blocked: { icon: "🔴", label: "blocked" },
  todo: { icon: "⚪", label: "todo" },
  "in-progress": { icon: "🔵", label: "in-progress" },
  "in-review": { icon: "🟡", label: "in-review" },
  done: { icon: "🟢", label: "done" },
};

const PHASE_NAMES = {
  0: "Documentation and bootstrap",
  1: "Foundation",
  2: "Logbook",
  3: "Calculation engine and E6B",
  4: "Aeronautical data",
  5: "Map, terrain and safe altitude",
  6: "OFP, weather and time marks",
  7: "FPL",
  8: "Settings and polish",
};

function parseScalar(raw) {
  const value = raw.trim();
  if (value === "[]") return [];
  if (value === "true") return true;
  if (value === "false") return false;
  if (/^-?\d+$/.test(value)) return Number(value);
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }
  if (value.startsWith("[") && value.endsWith("]")) {
    const inner = value.slice(1, -1).trim();
    if (!inner) return [];
    return inner.split(",").map((item) => item.trim()).filter(Boolean);
  }
  return value;
}

function parseFrontmatter(text, filename) {
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) {
    throw new Error(`${filename}: missing YAML frontmatter`);
  }
  const lines = match[1].split(/\r?\n/);
  const data = {};
  let currentList = null;

  for (const line of lines) {
    if (/^\s+-\s+/.test(line) && currentList) {
      data[currentList].push(line.replace(/^\s+-\s+/, "").trim());
      continue;
    }
    const kv = line.match(/^([A-Za-z0-9_]+):\s*(.*)$/);
    if (!kv) {
      if (line.trim() === "") continue;
      throw new Error(`${filename}: cannot parse frontmatter line: ${line}`);
    }
    const [, key, rest] = kv;
    if (rest === "" || rest === null) {
      currentList = key;
      data[key] = [];
      continue;
    }
    currentList = null;
    data[key] = parseScalar(rest);
  }
  return data;
}

function relPath(filename) {
  return `backlog/${filename}`;
}

function taskLink(task) {
  return `[${task.id}](${relPath(task.filename)})`;
}

function statusCell(status) {
  const meta = STATUS[status];
  if (!meta) throw new Error(`unknown status: ${status}`);
  return `${meta.icon} ${meta.label}`;
}

function todayStamp() {
  return new Date().toISOString().slice(0, 10);
}

function currentPhase(tasks) {
  const active = tasks.filter(
    (t) => t.status !== "done" && t.blocking !== true,
  );
  const pool = active.length > 0 ? active : tasks.filter((t) => t.status !== "done");
  if (pool.length === 0) return { n: null, label: "complete" };
  const n = Math.min(...pool.map((t) => t.phase));
  return { n, label: `${n} – ${PHASE_NAMES[n] ?? "Unknown"}` };
}

function counts(tasks) {
  const result = { blocked: 0, todo: 0, "in-progress": 0, "in-review": 0, done: 0 };
  for (const task of tasks) {
    if (!(task.status in result)) {
      throw new Error(`${task.id}: unknown status ${task.status}`);
    }
    result[task.status] += 1;
  }
  return result;
}

function table(rows) {
  const header = "| Id | Title | Est. | Status |";
  const sep = "|---|---|---|---|";
  return [header, sep, ...rows].join("\n");
}

function main() {
  const files = fs
    .readdirSync(BACKLOG_DIR)
    .filter((name) => name.endsWith(".md"))
    .sort();

  const tasks = files.map((filename) => {
    const text = fs.readFileSync(path.join(BACKLOG_DIR, filename), "utf8");
    const data = parseFrontmatter(text, filename);
    for (const required of ["id", "title", "status", "phase", "estimate"]) {
      if (data[required] === undefined) {
        throw new Error(`${filename}: missing ${required}`);
      }
    }
    return { ...data, filename };
  });

  tasks.sort((a, b) => a.id.localeCompare(b.id, "en"));

  const tally = counts(tasks);
  const phase = currentPhase(tasks);
  const blocking = tasks.filter((t) => t.blocking === true);

  const byPhase = new Map();
  for (const task of tasks) {
    const list = byPhase.get(task.phase) ?? [];
    list.push(task);
    byPhase.set(task.phase, list);
  }

  const lines = [];
  lines.push("<!-- GENERATED by `pnpm backlog:sync` from docs/backlog/*.md frontmatter.");
  lines.push("     Do not edit by hand – your changes will be overwritten.");
  lines.push("     The source of truth is each task file's frontmatter. -->");
  lines.push("");
  lines.push("# Backlog");
  lines.push("");
  lines.push(`**Generated:** ${todayStamp()} · **Current phase:** ${phase.label}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push("| Status | Count |");
  lines.push("|---|---|");
  lines.push(`| 🔴 blocked | ${tally.blocked} |`);
  lines.push(`| ⚪ todo | ${tally.todo} |`);
  lines.push(`| 🔵 in-progress | ${tally["in-progress"]} |`);
  lines.push(`| 🟡 in-review | ${tally["in-review"]} |`);
  lines.push(`| 🟢 done | ${tally.done} |`);
  lines.push("");

  lines.push("## Blocking");
  lines.push("");
  if (blocking.length === 0) {
    lines.push("_None._");
  } else {
    lines.push(
      table(
        blocking.map(
          (t) =>
            `| ${taskLink(t)} | ${t.title} | ${t.estimate} | ${statusCell(t.status)} |`,
        ),
      ),
    );
  }
  lines.push("");

  const fly002 = tasks.find((t) => t.id === "FLY-002");
  if (fly002) {
    lines.push(
      "> **FLY-002 gates all NOTAM work.** Requires FAA API credentials from the owner first.",
    );
    lines.push("> It does **not** gate Phase 1.");
    lines.push("");
  }

  const phases = [...byPhase.keys()].sort((a, b) => a - b);
  for (const n of phases) {
    const name = PHASE_NAMES[n] ?? "Unknown";
    lines.push(`## Phase ${n} – ${name}`);
    lines.push("");
    if (n === 0) {
      lines.push(
        table([
          "| – | Repository bootstrap, conventions, core documentation | – | 🟢 done (initial commit) |",
          ...byPhase.get(n).map(
            (t) =>
              `| ${taskLink(t)} | ${t.title} | ${t.estimate} | ${statusCell(t.status)} |`,
          ),
        ]),
      );
      lines.push("");
      lines.push(
        "Phase 0 documentation was written directly rather than tracked as individual tasks.",
      );
      lines.push("");
    } else {
      lines.push(
        table(
          byPhase.get(n).map(
            (t) =>
              `| ${taskLink(t)} | ${t.title} | ${t.estimate} | ${statusCell(t.status)} |`,
          ),
        ),
      );
      lines.push("");
      if (n === 1) {
        lines.push(
          "Suggested order: **FLY-010 → FLY-011**, then FLY-012 and FLY-013 in either order, then FLY-014",
        );
        lines.push(
          "(needs both). FLY-018 can start as soon as FLY-011 lands. FLY-015 / FLY-016 / FLY-017 need",
        );
        lines.push("FLY-013. FLY-019 needs FLY-014 and FLY-015.");
        lines.push("");
      }
    }
  }

  lines.push("## Legend");
  lines.push("");
  lines.push("| | |");
  lines.push("|---|---|");
  lines.push(
    "| **Est.** | S = under one agent budget · M = about one · L = **split it: it guarantees a mid-task handoff** |",
  );
  lines.push(
    "| **Status** | todo → in-progress → in-review → done · blocked |",
  );
  lines.push("");

  const output = lines.join("\n");
  const emDash = String.fromCharCode(0x2014);
  if (output.includes(emDash)) {
    throw new Error("backlog:sync produced an em-dash; rewrite the template");
  }
  fs.writeFileSync(OUT, output, "utf8");
  console.log(`wrote ${path.relative(ROOT, OUT)} (${tasks.length} tasks)`);
}

main();
